/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutSystemMonitoringRouteImport } from './routes/_layout/system-monitoring'
import { Route as LayoutSubscriptionRouteImport } from './routes/_layout/subscription'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReplyTemplatesRouteImport } from './routes/_layout/reply-templates'
import { Route as LayoutInquiriesRouteImport } from './routes/_layout/inquiries'
import { Route as LayoutIndustryConfigsRouteImport } from './routes/_layout/industry-configs'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCustomersRouteImport } from './routes/_layout/customers'
import { Route as LayoutChannelsRouteImport } from './routes/_layout/channels'
import { Route as LayoutBusinessesRouteImport } from './routes/_layout/businesses'
import { Route as LayoutOrganizationIndexRouteImport } from './routes/_layout/organization/index'
import { Route as LayoutOrganizationSettingsRouteImport } from './routes/_layout/organization/settings'
import { Route as LayoutOrganizationNewRouteImport } from './routes/_layout/organization/new'
import { Route as LayoutOrganizationMembersRouteImport } from './routes/_layout/organization/members'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemMonitoringRoute = LayoutSystemMonitoringRouteImport.update({
  id: '/system-monitoring',
  path: '/system-monitoring',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscriptionRoute = LayoutSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReplyTemplatesRoute = LayoutReplyTemplatesRouteImport.update({
  id: '/reply-templates',
  path: '/reply-templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInquiriesRoute = LayoutInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIndustryConfigsRoute = LayoutIndustryConfigsRouteImport.update({
  id: '/industry-configs',
  path: '/industry-configs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersRoute = LayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChannelsRoute = LayoutChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBusinessesRoute = LayoutBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationIndexRoute = LayoutOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationSettingsRoute =
  LayoutOrganizationSettingsRouteImport.update({
    id: '/organization/settings',
    path: '/organization/settings',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutOrganizationNewRoute = LayoutOrganizationNewRouteImport.update({
  id: '/organization/new',
  path: '/organization/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationMembersRoute =
  LayoutOrganizationMembersRouteImport.update({
    id: '/organization/members',
    path: '/organization/members',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/businesses': typeof LayoutBusinessesRoute
  '/channels': typeof LayoutChannelsRoute
  '/customers': typeof LayoutCustomersRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/industry-configs': typeof LayoutIndustryConfigsRoute
  '/inquiries': typeof LayoutInquiriesRoute
  '/reply-templates': typeof LayoutReplyTemplatesRoute
  '/settings': typeof LayoutSettingsRoute
  '/subscription': typeof LayoutSubscriptionRoute
  '/system-monitoring': typeof LayoutSystemMonitoringRoute
  '/users': typeof LayoutUsersRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/organization/members': typeof LayoutOrganizationMembersRoute
  '/organization/new': typeof LayoutOrganizationNewRoute
  '/organization/settings': typeof LayoutOrganizationSettingsRoute
  '/organization': typeof LayoutOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/businesses': typeof LayoutBusinessesRoute
  '/channels': typeof LayoutChannelsRoute
  '/customers': typeof LayoutCustomersRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/industry-configs': typeof LayoutIndustryConfigsRoute
  '/inquiries': typeof LayoutInquiriesRoute
  '/reply-templates': typeof LayoutReplyTemplatesRoute
  '/settings': typeof LayoutSettingsRoute
  '/subscription': typeof LayoutSubscriptionRoute
  '/system-monitoring': typeof LayoutSystemMonitoringRoute
  '/users': typeof LayoutUsersRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/organization/members': typeof LayoutOrganizationMembersRoute
  '/organization/new': typeof LayoutOrganizationNewRoute
  '/organization/settings': typeof LayoutOrganizationSettingsRoute
  '/organization': typeof LayoutOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/businesses': typeof LayoutBusinessesRoute
  '/_layout/channels': typeof LayoutChannelsRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/industry-configs': typeof LayoutIndustryConfigsRoute
  '/_layout/inquiries': typeof LayoutInquiriesRoute
  '/_layout/reply-templates': typeof LayoutReplyTemplatesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/subscription': typeof LayoutSubscriptionRoute
  '/_layout/system-monitoring': typeof LayoutSystemMonitoringRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/_layout/organization/members': typeof LayoutOrganizationMembersRoute
  '/_layout/organization/new': typeof LayoutOrganizationNewRoute
  '/_layout/organization/settings': typeof LayoutOrganizationSettingsRoute
  '/_layout/organization/': typeof LayoutOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/businesses'
    | '/channels'
    | '/customers'
    | '/dashboard'
    | '/industry-configs'
    | '/inquiries'
    | '/reply-templates'
    | '/settings'
    | '/subscription'
    | '/system-monitoring'
    | '/users'
    | '/invite/accept'
    | '/organization/members'
    | '/organization/new'
    | '/organization/settings'
    | '/organization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/businesses'
    | '/channels'
    | '/customers'
    | '/dashboard'
    | '/industry-configs'
    | '/inquiries'
    | '/reply-templates'
    | '/settings'
    | '/subscription'
    | '/system-monitoring'
    | '/users'
    | '/invite/accept'
    | '/organization/members'
    | '/organization/new'
    | '/organization/settings'
    | '/organization'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/businesses'
    | '/_layout/channels'
    | '/_layout/customers'
    | '/_layout/dashboard'
    | '/_layout/industry-configs'
    | '/_layout/inquiries'
    | '/_layout/reply-templates'
    | '/_layout/settings'
    | '/_layout/subscription'
    | '/_layout/system-monitoring'
    | '/_layout/users'
    | '/invite/accept'
    | '/_layout/organization/members'
    | '/_layout/organization/new'
    | '/_layout/organization/settings'
    | '/_layout/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system-monitoring': {
      id: '/_layout/system-monitoring'
      path: '/system-monitoring'
      fullPath: '/system-monitoring'
      preLoaderRoute: typeof LayoutSystemMonitoringRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscription': {
      id: '/_layout/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof LayoutSubscriptionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reply-templates': {
      id: '/_layout/reply-templates'
      path: '/reply-templates'
      fullPath: '/reply-templates'
      preLoaderRoute: typeof LayoutReplyTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inquiries': {
      id: '/_layout/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof LayoutInquiriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/industry-configs': {
      id: '/_layout/industry-configs'
      path: '/industry-configs'
      fullPath: '/industry-configs'
      preLoaderRoute: typeof LayoutIndustryConfigsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/channels': {
      id: '/_layout/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof LayoutChannelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/businesses': {
      id: '/_layout/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof LayoutBusinessesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organization/': {
      id: '/_layout/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof LayoutOrganizationIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organization/settings': {
      id: '/_layout/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof LayoutOrganizationSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organization/new': {
      id: '/_layout/organization/new'
      path: '/organization/new'
      fullPath: '/organization/new'
      preLoaderRoute: typeof LayoutOrganizationNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organization/members': {
      id: '/_layout/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof LayoutOrganizationMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBusinessesRoute: typeof LayoutBusinessesRoute
  LayoutChannelsRoute: typeof LayoutChannelsRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutIndustryConfigsRoute: typeof LayoutIndustryConfigsRoute
  LayoutInquiriesRoute: typeof LayoutInquiriesRoute
  LayoutReplyTemplatesRoute: typeof LayoutReplyTemplatesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubscriptionRoute: typeof LayoutSubscriptionRoute
  LayoutSystemMonitoringRoute: typeof LayoutSystemMonitoringRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutOrganizationMembersRoute: typeof LayoutOrganizationMembersRoute
  LayoutOrganizationNewRoute: typeof LayoutOrganizationNewRoute
  LayoutOrganizationSettingsRoute: typeof LayoutOrganizationSettingsRoute
  LayoutOrganizationIndexRoute: typeof LayoutOrganizationIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBusinessesRoute: LayoutBusinessesRoute,
  LayoutChannelsRoute: LayoutChannelsRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutIndustryConfigsRoute: LayoutIndustryConfigsRoute,
  LayoutInquiriesRoute: LayoutInquiriesRoute,
  LayoutReplyTemplatesRoute: LayoutReplyTemplatesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubscriptionRoute: LayoutSubscriptionRoute,
  LayoutSystemMonitoringRoute: LayoutSystemMonitoringRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutOrganizationMembersRoute: LayoutOrganizationMembersRoute,
  LayoutOrganizationNewRoute: LayoutOrganizationNewRoute,
  LayoutOrganizationSettingsRoute: LayoutOrganizationSettingsRoute,
  LayoutOrganizationIndexRoute: LayoutOrganizationIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteAcceptRoute: InviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
