export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Domain-specific (users/sessions)
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  NOT_YOUR_SESSION = 'NOT_YOUR_SESSION',
  PASSWORD_NOT_SET = 'PASSWORD_NOT_SET',
  PASSWORD_INVALID = 'PASSWORD_INVALID',

  // Consents/Policy
  POLICY_NOT_FOUND = 'POLICY_NOT_FOUND',

  // Content/Category/Terms
  CATEGORY_SLUG_EXISTS = 'CATEGORY_SLUG_EXISTS',
  TERM_NOT_FOUND = 'TERM_NOT_FOUND',
  TERM_SLUG_EXISTS = 'TERM_SLUG_EXISTS',
  EXPRESSION_NOT_FOUND = 'EXPRESSION_NOT_FOUND',
  EXPRESSION_SLUG_EXISTS = 'EXPRESSION_SLUG_EXISTS',
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  TAG_SLUG_EXISTS = 'TAG_SLUG_EXISTS',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_SLUG_EXISTS = 'COURSE_SLUG_EXISTS',
  LESSON_NOT_FOUND = 'LESSON_NOT_FOUND',
  VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND',
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  S3_OBJECT_NOT_FOUND = 'S3_OBJECT_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  FOLDER_NOT_FOUND = 'FOLDER_NOT_FOUND',
  ONBOARDING_REQUIRED = 'ONBOARDING_REQUIRED',

  // Auth / Tokens
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_SESSION_BLOCKED = 'REFRESH_SESSION_BLOCKED',

  // Social auth
  SOCIAL_TOKEN_INVALID = 'SOCIAL_TOKEN_INVALID',
  SOCIAL_ISSUER_INVALID = 'SOCIAL_ISSUER_INVALID',
  SOCIAL_AUDIENCE_INVALID = 'SOCIAL_AUDIENCE_INVALID',
  SOCIAL_SIGNATURE_INVALID = 'SOCIAL_SIGNATURE_INVALID',
  SOCIAL_PROVIDER_UNSUPPORTED = 'SOCIAL_PROVIDER_UNSUPPORTED',
  SOCIAL_NETWORK_ERROR = 'SOCIAL_NETWORK_ERROR',

  // Notifications
  NOTIFICATION_LOG_NOT_FOUND = 'NOTIFICATION_LOG_NOT_FOUND',
}
